[book]
authors = ["Tethys Svensson"]
language = "en"
multilingual = false
src = "src"
title = "GPU learning"

[output.html]
additional-css = ["theme/language-style.css"]
additional-js = ["theme/language-style.js"]
mathjax-support = true

[preprocessor.index]
[preprocessor.classy]
