[package]
name = "read-bmp-rs"
version = "0.1.0"
authors = ["Tethys Svensson <freaken@freaken.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
