site_name: GPU Learning

theme:
  name: material

nav:
- Introduction: 'index.md'
- Getting started:
    - Overview: 'getting-started.md'
    - 'Native': 'native.md'
    - 'Directives': 'directives.md'
- Memory:
    - Overview: 'memory.md'
    - 'Coalescing': 'memory-coalescing.md'
    - 'Management': 'memory-management.md'
    - 'Shared': 'shared-memory.md'
- Overlapping data transfers: 'overlapping.md'
- Error handling: 'error-handling.md'
- Exploiting parallelism: 'exploiting-parallelism.md'
- Further reading: 'further-reading.md'

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js